name: freedom-guard
version: '$(node -p "require('./package.json').version")'
summary: Freedom Guard is a tool for bypassing internet censorship.
description: |
    Freedom Warp+ Freedom Vibe+ Freedom Browser+.

grade: stable
confinement: strict

base: core18  

apps:
  freedom-guard:
    command: freedom-guard
    plugs:
      - network
      - network-bind
      - desktop
      - x11
    desktop: share/applications/freedom-guard.desktop

parts:
  freedom-guard:
    plugin: nodejs
    source: .
    build-packages:
      - libgtk-3-dev 
      - libx11-dev     
      - libdbus-1-dev  
    stage-packages:
      - libx11-6
      - libdbus-1-3
      - libatk1.0-0
      - libgdk-pixbuf2.0-0
      - libnspr4
      - libnss3
      - libxss1
      - libxtst6
    after:
      - desktop-gtk3
